# Generated by Django 5.1.5 on 2025-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='image_card',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
    ]
