# Generated by Django 5.1.5 on 2025-01-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_description_card_test_image_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
