# Generated by Django 5.1.5 on 2025-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image_card',
            field=models.ImageField(blank=True, null=True, upload_to='test/', verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
